# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelubbr',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
